package vn.shp.portal.entity;

import lombok.Data;

import javax.persistence.*;

/**
 * This class was automatically generated by the data modeler tool.
 */

@Entity
@Table(name = "ALF_FILE")
@Data
public class AlfFile implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "ALF_FILE_ID_SEQ")
    @SequenceGenerator(name = "ALF_FILE_ID_SEQ", sequenceName = "ALF_FILE_SEQ", allocationSize = 1)
    @Column(name = "id")
    private Long id;

    @Column(name = "NAME", length = 250)
    private String name;

    @Column(name = "TYPE", length = 50)
    private String type;

    @Column(name = "UUID", length = 250)
    private String uuid;

    @Column(name = "FILE_NAME", length = 250)
    private String fileName;

    @Column(name = "SOURCE", length = 250)
    private String source;

    @Column(name = "SOURCE_ID")
    private Long sourceId;

    @Column(name = "NOTE", length = 500)
    private String note;

    @javax.persistence.Transient
    private String url;

    public AlfFile() {
        super();
    }

    public AlfFile(String name, String type, String uuid, String fileName, String source, Long sourceId) {
        super();
        this.name = name;
        this.type = type;
        this.uuid = uuid;
        this.fileName = fileName;
        this.source = source;
        this.sourceId = sourceId;
    }

    public String getUrl() {
        if (this.uuid != null) {
            String fullUuid[] = uuid.split(";");
            if (fullUuid.length == 2) {
                url = fullUuid[0] + "|" + fullUuid[1].replace(".", "_");
            }

        } else {
            url = uuid;
        }
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        AlfFile other = (AlfFile) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        return true;
    }


}